name: mukhliss
description: "Application de fidélité client Mukhliss - Gestion des offres et récompenses."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.5+9

flutter_icons:
  android: true
  ios: true
  image_path: "images/mukhlis1.png"

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.0.0
  flutter_dotenv: ^5.1.0
  connectivity_plus: ^5.0.0
  shared_preferences: ^2.2.2
  get: ^4.7.2
  flutter_riverpod: ^2.5.1
  google_sign_in: ^6.3.0
  sign_in_with_apple: ^6.1.4
  crypto: ^3.0.6
  qr_flutter: ^4.1.0
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.8
  flutter_facebook_auth: ^7.1.2
  device_info_plus: ^10.1.0
  tuple: ^2.0.0
  shimmer: ^2.0.0
  uuid: ^4.5.2
  package_info_plus: ^8.3.0
  geolocator: ^13.0.0
  flutter_map: ^8.1.1
  flutter_polyline_points: ^2.1.0
  flutter_map_marker_cluster: ^8.2.2
  latlong2: ^0.9.1
  http: ^1.4.0
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  url_launcher: ^6.1.11
  internet_connection_checker_plus: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image: ^4.6.0

  # ============================================
  # DEV DEPENDENCIES - Pour les tests et le développement
  # ============================================
  path_provider: any
  flutter_secure_storage: ^9.2.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.13

flutter:
  generate: true
  uses-material-design: true

  # Assets configuration
  assets:
    - .env
    - images/withoutbg.png
    - images/google_logo.png
    - images/facbook.jpeg
    - images/offer_pattern.png
    - images/withoutbackgroundwhite.png
    - images/mukhlis.png
    - images/mukhlis1.png
    - images/mukhlislogo.png
    - images/mukhlislogo1.png
    - images/placeholder.jpg
    - images/whitemukhlislogo.png

  # Fonts configuration
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
